package blog.anirbanm.prog.model.am;

import blog.anirbanm.prog.model.am.common.ProgramModule;
import blog.anirbanm.prog.model.vo.EmployeesPVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 16 12:02:53 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProgramModuleImpl extends ApplicationModuleImpl implements ProgramModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ProgramModuleImpl() {
    }
    
    public void execute(final Integer departmentId) {
        System.out.println("Searching for department " + departmentId);
        final EmployeesPVOImpl empView = getEmployeesPVO1();
        empView.setDepartmentId(departmentId == null ? -1 : departmentId);
        empView.executeQuery();
    }

    /**
     * Container's getter for EmployeesPVO1.
     * @return EmployeesPVO1
     */
    public EmployeesPVOImpl getEmployeesPVO1() {
        return (EmployeesPVOImpl) findViewObject("EmployeesPVO1");
    }
}

