package blog.anirbanm.prog.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 16 12:04:47 IST 2018
// ---------------------------------------------------------------------
public interface ProgramModule extends ApplicationModule {
    void execute(Integer departmentId);
}

